export const cards: { name: string, value: number | number[] }[] = [
    { name: 'club_10.svg', value: 10 },
    { name: 'club_2.svg', value: 2 },
    { name: 'club_3.svg', value: 3 },
    { name: 'club_4.svg', value: 4 },
    { name: 'club_5.svg', value: 5 },
    { name: 'club_6.svg', value: 6 },
    { name: 'club_7.svg', value: 7 },
    { name: 'club_8.svg', value: 8 },
    { name: 'club_9.svg', value: 9 },
    { name: 'club_a.svg', value: [1, 11] },
    { name: 'club_j.svg', value: 10 },
    { name: 'club_k.svg', value: 10 },
    { name: 'club_q.svg', value: 10 },
    { name: 'diamond_10.svg', value: 10 },
    { name: 'diamond_2.svg', value: 2 },
    { name: 'diamond_3.svg', value: 3 },
    { name: 'diamond_4.svg', value: 4 },
    { name: 'diamond_5.svg', value: 5 },
    { name: 'diamond_6.svg', value: 6 },
    { name: 'diamond_7.svg', value: 7 },
    { name: 'diamond_8.svg', value: 8 },
    { name: 'diamond_9.svg', value: 9 },
    { name: 'diamond_a.svg', value: [1, 11] },
    { name: 'diamond_j.svg', value: 10 },
    { name: 'diamond_k.svg', value: 10 },
    { name: 'diamond_q.svg', value: 10 },
    { name: 'heart_10.svg', value: 10 },
    { name: 'heart_2.svg', value: 2 },
    { name: 'heart_3.svg', value: 3 },
    { name: 'heart_4.svg', value: 4 },
    { name: 'heart_5.svg', value: 5 },
    { name: 'heart_6.svg', value: 6 },
    { name: 'heart_7.svg', value: 7 },
    { name: 'heart_8.svg', value: 8 },
    { name: 'heart_9.svg', value: 9 },
    { name: 'heart_a.svg', value: [1, 11] },
    { name: 'heart_j.svg', value: 10 },
    { name: 'heart_k.svg', value: 10 },
    { name: 'heart_q.svg', value: 10 },
    { name: 'spade_10.svg', value: 10 },
    { name: 'spade_2.svg', value: 2 },
    { name: 'spade_3.svg', value: 3 },
    { name: 'spade_4.svg', value: 4 },
    { name: 'spade_5.svg', value: 5 },
    { name: 'spade_6.svg', value: 6 },
    { name: 'spade_7.svg', value: 7 },
    { name: 'spade_8.svg', value: 8 },
    { name: 'spade_9.svg', value: 9 },
    { name: 'spade_a.svg', value: [1, 11] },
    { name: 'spade_j.svg', value: 10 },
    { name: 'spade_k.svg', value: 10 },
    { name: 'spade_q.svg', value: 10 }
];
export const cardBack: string = '/card_back.svg';

export const chips = [
    { name: 'chip_1.png', value: 1 },
    { name: 'chip_5.png', value: 5 },
    { name: 'chip_25.png', value: 25 },
    { name: 'chip_50.png', value: 50 },
    { name: 'chip_100.png', value: 100 },
    { name: 'chip_500.png', value: 500 }
];